language: ruby
cache: bundler
sudo: false
rvm: 2.4.0
install:
- bundle install
- bundle exec rake prebuild:install
script:
- bundle exec rake build:prod
- bundle exec rake postbuild:test
addons:
  ssh_known_hosts: ssh-sudweb.alwaysdata.net
before_deploy:
- eval "$(ssh-agent -s)"
- chmod 600 $TRAVIS_BUILD_DIR/deploy_rsa
- ssh-add $TRAVIS_BUILD_DIR/deploy_rsa
after_deploy:
- ssh-agent -k
deploy:
  provider: script
  skip_cleanup: true
  script: bundle exec rake postbuild:deploy
  on:
    branch: master
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - WEEZEVENT_EVENT_ID=218160
before_deploy:
- openssl aes-256-cbc -K $encrypted_2733e3f99a07_key -iv $encrypted_2733e3f99a07_iv
  -in deploy_rsa.enc -out deploy_rsa -d
