# Site configuration

title: Sud Web
tagline: les 25 et 26 mai 2018 à Anduze
description: Deux journées pour faire le plein d'inspiration entre super-héros du web.
logo: /assets/images/twittercard.png
url: https://sudweb.fr
repository: sudweb/2018
baseurl: /2018
locale: fr_FR
logo: https://sudweb.fr/2018/assets/images/social/sudweb-logo.jpg

## SEO

robots: index,follow
twitter:
  username: SudWeb
image:
  path: /assets/images/twittercard.png
  height: 200
  width: 200
social:
  type: organization
  links:
    - https://twitter.com/SudWeb
    - https://www.facebook.com/SudWeb
facebook:
  publisher: https://www.facebook.com/SudWeb/

github:
  url: https://sudweb.fr/2018

# Services configuration

weezevent:
    mini-site-url: https://www.weezevent.com/sudweb-2018

newsletter:
  url: http://sudweb.us2.list-manage.com/subscribe?u=af19b58cf514c01eca3f7652e&id=b579f5b507

# Jekyll configuration

timezone: Europe/Paris
sass:
    sass_dir: _sass
    style: compressed

defaults:
  -
    scope:
      path: "pages"
      type: pages
    values:
      locale: fr_FR
      layout: default
  -
    scope:
      path: "pages/en"
      type: pages
    values:
      baseurl: "/2018/en"
      locale: en_US

include:
  - _headers

exclude:
  - .editorconfig
  - .gitattributes
  - .gitignore
  - .ruby-version
  - .travis.yml
  - autoprefixer.yml
  - Gemfile
  - Gemfile.lock
  - Procfile
  - script
  - vendor
  - gems
  - tmp
  - LICENSE
  - README.md
  - notes-integration.md
  - script

plugins:
  - jekyll-github-metadata
  - jekyll-sitemap
  - jekyll-redirect-from
  - octopress-autoprefixer
