# Site configuration

title: We ❤️ Speed
tagline: le 9 octobre 2018 à Bordeaux
description: La conférence faite par et pour les experts de la Performance Web
logo: /assets/images/twittercard.png
url: https://welovespeed.com/
mail: contact@welovespeed.com
social:
  twitter: borisschapira
repository: welovespeed/welovespeed.com
baseurl: ""
destination: _site/
locale: fr_FR
logo: https://welovespeed.com/assets/images/social/logo.jpg
lazyload:
  placeholder: "data:image/gif;base64,R0lGODlhAQABAIAAAAAAAAAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw=="

# Est-ce qu'on vend des places à tarif plein, est-ce qu'on propose une liste d'attente ou les deux ?
tickets:
  selling: false
  waiting-list: false

# Compression du code HTML en production
compress_html:
  ignore:
    envs:
      - 'development'

## SEO

robots: noindex,nofollow

# Services configuration

weezevent:
    mini-site-url: https://www.weezevent.com/welovespeed-2018

newsletter:
  display: false
  url: ""

# Jekyll configuration

timezone: Europe/Paris
sass:
    sass_dir: _sass
    style: compressed

collections:
  talks:
    output: false
    order: date asc
    permalink: /talks/:path/
    sitemap: false

defaults:
  -
    scope:
      path: "pages"
      type: pages
    values:
      locale: fr_FR
      layout: default
  -
    scope:
      path: "pages/en"
      type: pages
    values:
      baseurl: "/2018/en"
      locale: en_US

microtypo:
  median: true

include:
  - _headers

exclude:
  - .editorconfig
  - .gitattributes
  - .gitignore
  - .ruby-version
  - .travis.yml
  - autoprefixer.yml
  - Gemfile
  - Gemfile.lock
  - Procfile
  - script
  - vendor
  - gems
  - tmp
  - LICENSE
  - README.md
  - notes-integration.md
  - script
  - "Rakefile"
  - "gulpfile.js"
  - "node_modules"
  - "package.json"
  - "package-lock.json"
